name: CICD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

  jobs:
      - name: InitierEtValiderTerraform
        steps:
          - name: Checkout
            uses: actions/checkout@v2

          - name: InitierTerraform
            run: terraform init

          - name: ValiderTerraform
            run: terraform validate

  jobs:
      - name: PlanDeTerraform
        steps:
          - name: Checkout
            uses: actions/checkout@v2

          - name: TerraformPlan
            run: terraform plan 

  jobs:
        name: ValidationManuelle
        steps:
        - name: Approuver
          id: approuver
          run: echo "Appuyer pour approuver"

        - name: DeployerTerraform
          if: github.event_name == 'workflow_run' && github.event.workflow_run.event == 'APPROVED'
          run: terraform apply 
