name: CICD
on:
  push:
    branches:
        - main
  pull_request:
    branches:
        - main
jobs:
  Terraform:
    name: terraform
    runs-on: ubuntu-latest
    steps:
      - name: ConnexionAzure
        working-directory: ./TP-terraform
        run: az login -u ${{secret.AZURE_USER}} -p ${{secret.AZURE_PASSWD}}
      - name: Checkout
        uses: actions/checkout@v2
      - name: InitierTerraform
        working-directory: ./TP-terraform
        run: terraform init
      - name: ValiderTerraform
        working-directory: ./TP-terraform
        run: terraform validate
      - name: TerraformPlan
        working-directory: ./TP-terraform
        run: terraform plan
      - name: Approuver
        id: approuver
        run: echo "Appuyer pour approuver"
      - name: DeployerTerraform
        working-directory: ./TP-terraform
        if: >-
           github.event_name == 'workflow_run' &&
           github.event.workflow_run.event == 'APPROVED'
        run: terraform apply
