name: CICD
on:
  push:
    branches:
        - main
  pull_request:
    branches:
        - main
jobs:
  Terraform:
    name: terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: InitierTerraform
        run: terraform init
      - name: ValiderTerraform
        run: terraform validate
      - name: TerraformPlan
        run: terraform plan --kubeconfig ../TP-terraform/.kube/config
      - name: Approuver
        id: approuver
        run: echo "Appuyer pour approuver"
      - name: DeployerTerraform
        if: >-
           github.event_name == 'workflow_run' &&
           github.event.workflow_run.event == 'APPROVED'
        run: terraform apply
