name: CICD
on:
  push:
    branches:
        - main
  pull_request:
    branches:
        - main
jobs:
  Terraform:
    name: terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: ConnexionAzure
        working-directory: ./TP-terraform
        run: az login -u ${{secrets.AZURE_USER}} -p ${{secrets.AZURE_PASSWD}}
      - name: InitierTerraform
        working-directory: ./TP-terraform
        run: terraform init
      - name: ValiderTerraform
        working-directory: ./TP-terraform
        run: terraform validate
      - name: TerraformPlan
        working-directory: ./TP-terraform
        run: terraform plan
      - name: Approuver
        id: approuver
        run: echo "Appuyer pour approuver"
      - name: DeployerTerraform
        working-directory: ./TP-terraform
      - name: Valider
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{secrets.TOKEN_VALIDATION}}
          approvers: csubirana
          minimum-approvals: 1
          run: terraform apply
